name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or the branch you use for your source code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is the crucial line to add

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Or your Node.js version

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
